name: Build Windows Executable

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-windows-executable:
    name: Build Executable on Windows
    runs-on: windows-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install WiX Toolset (Required for jpackage)
        run: choco install wixtoolset -y
      
      - name: Install Maven
        run: choco install maven -y
  
      - name: Build the jar with maven
        run: |
          mvn clean package
          
      - name: Run Windows build script
        run: |
            cd build
            chmod +x buildWindows.bat
            ./buildWindows.bat

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: output/*
