name: Build Mac DMG

on:
  workflow_call:

jobs:
  build-windows-executable:
    name: Build Mac DmG
    runs-on: macos-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Extract Version from Tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build the jar with maven
        run: |
          ./mvnw clean package
          
      - name: Run macos build script
        run: |
            chmod +x buildmac.sh
            ./buildmac.sh

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-installer
          path: output/*
