name: CI Build (Runs on Every Push)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'  
          distribution: 'graalvm'  
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Java and GraalVM Setup
        run: |
          echo "JAVA_HOME is: $JAVA_HOME"
          echo "GRAALVM_HOME is: $GRAALVM_HOME"
          ls -lah $JAVA_HOME/bin
          java -version
          native-image --version

      - name: Build Java Application
        run: mvn clean package

      - name: List Files in Target (Debugging)
        run: ls -lah target/

      - name: Build Native Image
        run: |
          export JAVA_HOME=$GRAALVM_HOME
          export PATH=$JAVA_HOME/bin:$PATH
          native-image -jar target/link-mon-1.0-SNAPSHOT.jar -o target/link-mon

      - name: Upload Native Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: link-mon-native
          path: target/link-mon
