name: Build Windows Executable

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build-windows-executable:
    name: Build Executable on Windows
    runs-on: windows-latest  # Running on a Windows GitHub-hosted runner

    steps:
      # SETUP BUILD ENVIRONMENT
      - id: checkout-code
        name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master  # Checkout the latest code from the master branch

      - id: setup-jdk
        name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # Using Adoptium (temurin) for Java 17
          java-version: 17  # Specify Java version 17

      - id: install-wix
        name: Install WiX Toolset (Required for jpackage)
        run: choco install wixtoolset -y  # Installs WiX on the runner
      
      - id: install-maven
        name: Install Maven
        run: choco install maven -y
  
      - id: build-jar
        name: Build the jar with maven
        run: |
          maven clean package
          dir target  # Windows equivalent of 'ls -la'
          if not exist target\link-mon-1.0-SNAPSHOT.jar (
            echo "ERROR: JAR file not found in target/"
            exit 1
          )

      - id: build-exe
        name: Run Windows build script
        run: |
            chmod +x buildWindows.bat
            ./buildWindows.bat
          
      - id: check
        name: check dir
        run: |
          echo "Listing files in the build directory:"
          dir ./output

      # SAVE THE EXECUTABLE
      - id: upload-executable
        name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          path: output/  # Correct path to the generated executable
          name: windows-installer
          retention-days: 1  # Retain the artifact for 1 day
