name: Build Windows Executable

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build-windows-executable:
    name: Build Executable on Windows
    runs-on: windows-latest  # Running on a Windows GitHub-hosted runner

    steps:
      # SETUP BUILD ENVIRONMENT
      - id: checkout-code
        name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main  # Checkout the latest code from the main branch

      - id: setup-jdk
        name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Using Adoptium (temurin) for Java 17
          java-version: 17  # Specify Java version 17

      # BUILD FOR DISTRIBUTION (Windows Executable)
      - id: build
        name: Build Windows Executable
        run: |
          mvn clean package  # Clean and build the project using Maven
          jpackage --verbose --input . --name LinkMon --main-jar link-mon-1.0-SNAPSHOT.jar --main-class com.morizkraemer.App --type exe

      # SAVE THE EXECUTABLE
      - id: upload-executable
        name: Upload Windows Executable
        uses: actions/upload-artifact@v3
        with:
          path: ./LinkMon.exe  # Path to the generated executable (in the main directory)
          name: windows-executable  # Name of the artifact to upload
          retention-days: 1  # Retain the artifact for 1 day
