name: Release Controller

on:
  push:
    tags:
      - "v*"  # Trigger when a new version tag is pushed

jobs:
  build-windows:
    uses: ./.github/workflows/build_windows.yml

  build-macos:
    uses: ./.github/workflows/build_mac.yml

  build-linux:
    uses: ./.github/workflows/build_jar.yml

  create-release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-installer
          path: all-artifacts/windows/

      - name: Download macOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-installer
          path: all-artifacts/macos/

      - name: Download jar Artifact
        uses: actions/download-artifact@v4
        with:
          name: fat-jar
          path: all-artifacts/jar/

      - name: check dirs
        run: |
          ls -R all-artifacts/

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body: "Automated release for version ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Find Windows Artifact
        run: |
          WINDOWS_FILE=$(find all-artifacts/windows -type f -name "*.exe")
          echo "WINDOWS_FILE=$WINDOWS_FILE" >> $GITHUB_ENV

      - name: Upload Windows Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.WINDOWS_FILE }}
          asset_name: Link-Mon-Installer_AMD64.exe
          asset_content_type: application/octet-stream

      - name: Find macOS Artifact
        run: |
          MACOS_FILE=$(find all-artifacts/macos -type f -name "*.dmg")
          echo "MACOS_FILE=$MACOS_FILE" >> $GITHUB_ENV

      - name: Upload macOS Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.MACOS_FILE }}
          asset_name: Link-Mon_ARM64.dmg
          asset_content_type: application/octet-stream

      - name: Find Linux Artifact
        run: |
          JAR_FILE=$(find all-artifacts/jar -type f -name "*.jar")
          echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV

      - name: Upload Linux Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.JAR_FILE }}
          asset_name: Link-Mon_FAT-JAR.jar
          asset_content_type: application/octet-stream
