name: Release Controller

on:
  push:
    tag:
      - "v*"  # Trigger when a new version tag is pushed

jobs:
  build-windows:
    uses: ./.github/workflows/build_windows.yml

  build-macos:
    uses: ./.github/workflows/build_mac.yml

  build-linux:
    uses: ./.github/workflows/build_jar.yml

  create-release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-installer
          path: all-artifacts/windows/

      - name: Download macOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-installer
          path: all-artifacts/macos/

      - name: Download jar Artifact
        uses: actions/download-artifact@v4
        with:
          name: fat-jar
          path: all-artifacts/jar/

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body: "Automated release for version ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload Windows Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: all-artifacts/windows/*
          asset_name: Link-Mon-Installer_AMD64.exe
          asset_content_type: application/octet-stream

      - name: Upload macOS Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: all-artifacts/macos/*
          asset_name: Link-Mon_ARM64.dmg
          asset_content_type: application/octet-stream

      - name: Upload Linux Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: all-artifacts/jar/*
          asset_name: Link-mon_FAT-JAR.jar
          asset_content_type: application/octet-stream
